apiVersion: v1
kind: ConfigMap
metadata:
  name: camel-rest-service-configmap
data:
    DATABASE_URL: jdbc:oracle:thin:@10.46.90.192:1521/TIMOBG
    DATABASE_USR: GUP
    NETS_PROTOCOL: https
    NETS_HOST: testeps.netswgroup.it
    NETS_PORT: "443"
    NETS_PAYMENT_CONFIRMBILL_URI: /TIM_CG_SERVICES/pgw/payment/capture
    NETS_HTTP_TIMEOUT: "30000"
    LOG_DEST: <OCPLOGDEST="LOGGA">
    LOG_LEVEL_ROOT: ERROR
    LOG_LEVEL_PAYMENT_CONFIRMBILL: INFO
    SDP_HOST: "10.21.100.175"
    SDP_PORT: "8888"
    SDP_PROTOCOL: https
    SDP_HTTP_TIMEOUT: "10000"
    SDP_STATO_FATTURE_URI: /clienti/{rifCliente}/statoFatture/pagamenti
    SDP_FLAG_ASYNC: "false"
    RABBITMQ_QUEUE: gup.internal.sdp.notify
    GREETING_PREFIX: ciaociao