FROM openjdk:8-jre-alpine

ADD camel-rest-service-0.1.0.jar camel-rest-sample/camel-rest-service/camel-rest-service-0.1.0.jar

CMD java -jar camel-rest-sample/camel-rest-service/camel-rest-service-0.1.0.jar